### ISSUE TITLE
get_bpm returning None instead of float?

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [elixirbeats/abletoolz#16]
Hi, thanks for making this tool available, I am excited to have it streamline my workflow across a bunch of different workstations!

I'm running into an error when using the `--check-samples` flag - I see the following error output, which indicates the BPM is not being read/accessed successfully. For what it's worth, when opening the set in Live I see the BPM set to 151 and playback works fine... Here's the error:

` abletoolz .\Wet.als --check-samples
Parsing: Wet.als
Set version: Ableton Live 12.0.10
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\nfeeh\AppData\Roaming\Python\Python312\Scripts\abletoolz.exe\__main__.py", line 7, in <module>
  File "C:\Users\nfeeh\AppData\Roaming\Python\Python312\site-packages\abletoolz\cli.py", line 356, in main
    sys.exit(process(args))
             ^^^^^^^^^^^^^
  File "C:\Users\nfeeh\AppData\Roaming\Python\Python312\site-packages\abletoolz\cli.py", line 335, in process
    process_set(args, pathlib_obj, db)
  File "C:\Users\nfeeh\AppData\Roaming\Python\Python312\site-packages\abletoolz\cli.py", line 242, in process_set
    logger.info("%sSet name: %s, %sBPM: %s", C, pathlib_obj.stem, B, ableton_set.get_bpm())
                                                                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nfeeh\AppData\Roaming\Python\Python312\site-packages\abletoolz\ableton_set.py", line 69, in wrapped_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nfeeh\AppData\Roaming\Python\Python312\site-packages\abletoolz\ableton_set.py", line 337, in get_bpm
    self.bpm = round(float(bpm_elem), 6)
                     ^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'`

...is there potentially something wrong with my setup? Or possibly this is a new problem with Live 12?

Thanks for any help you can provide!

AKA

**Comment by elixirbeats** [comment]
Hi AKA, 

Most likely that is a change with Live 12 set hierarchy, I will try to get around to digging in and adding support for 12 in the near future.
